# Load user specific variables and API KEYS
[[ -s "$HOME/dotfiles/.user_variables" ]] && source "$HOME/dotfiles/.user_variables"

# Append Homebrew path before system bin
[[ -s "$HOME/.bash_path" ]] && source "$HOME/.bash_path"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# This loads NVM
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh

# Load environment variables for development
[[ -s "$HOME/.environment_variables" ]] && source "$HOME/.environment_variables"

# Load terminal prompt scripts
[[ -s "$HOME/.bash_prompt" ]] && source "$HOME/.bash_prompt"

# Load aliases
[[ -s "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Use Homebrew bash completion
if type "brew" &> /dev/null && [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if type "direnv" &> /dev/null; then
  eval "$(direnv hook bash)"
fi

function vudo() {  
  eval "vagrant ssh -c \"cd /vagrant && $@\""
}

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /Users/paul/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash ] && . /Users/paul/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /Users/paul/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash ] && . /Users/paul/.nvm/versions/node/v8.6.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash